# Generated by Django 5.2.8 on 2025-11-15 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('tipo', models.CharField(choices=[('OSTEOPATIA_MASAJE', 'Osteopatía y Masaje Holístico'), ('PAR_MAGNETICO', 'Par Biomagnético Equilibrado'), ('TECNICAS_EMOCIONALES', 'Técnicas Emocionales Adaptadas'), ('ASESORAMIENTO_NUTRICIONAL', 'Asesoramiento Nutricional')], default='OSTEOPATIA_MASAJE', max_length=30)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_appointments', to='worker.worker')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
