# Generated by Django 5.2.8 on 2025-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="fecha",
            new_name="datetime",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="estado",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="trabajador",
            new_name="worker",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="tipo",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("OSTEOPATIA_MASAJE", "Osteopatía y Masaje Holístico"),
                    ("PAR_MAGNETICO", "Par Biomagnético Equilibrado"),
                    ("TECNICAS_EMOCIONALES", "Técnicas Emocionales Adaptadas"),
                    ("ASESORAMIENTO_NUTRICIONAL", "Asesoramiento Nutricional"),
                    ("OTRO", "Otro"),
                ],
                default="OSTEOPATIA_MASAJE",
                max_length=30,
            ),
        ),
    ]
