# Generated by Django 5.2.7 on 2025-11-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='worker',
            name='specialty',
            field=models.CharField(choices=[('TYPE1', 'T1'), ('TYPE2', 'T2'), ('TYPE3', 'T3')], default='TYPE1', max_length=20),
        ),
    ]
