# Generated by Django 5.2.7 on 2025-11-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_rename_nombre_worker_name_remove_worker_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='specialty',
            field=models.CharField(choices=[('Masaje', 'Osteopatía y Masaje Holístico'), ('ParBiomagnético', 'Par Biomagnético Equilibrado'), ('TécnicasEmocionales', 'Técnicas Emocionales Adaptadas'), ('AsesoramientoNutricional', 'Asesoramiento\xa0Nutricional'), ('Otro', 'Otro')], default='Otro', max_length=50),
        ),
    ]
