# Generated by Django 5.2.8 on 2025-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0003_alter_worker_specialty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("OSTEOPATIA_MASAJE", "Osteopatía y Masaje Holístico"),
                    ("PAR_MAGNETICO", "Par Biomagnético Equilibrado"),
                    ("TECNICAS_EMOCIONALES", "Técnicas Emocionales Adaptadas"),
                    ("ASESORAMIENTO_NUTRICIONAL", "Asesoramiento Nutricional"),
                    ("OTRO", "Otro"),
                ],
                default="OTRO",
                max_length=50,
            ),
        ),
    ]
