# Generated by Django 5.2.7 on 2025-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_worker_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OSTEOPATIA_MASAJE', 'Osteopatía y Masaje Holístico'), ('PAR_MAGNETICO', 'Par Biomagnético Equilibrado'), ('TECNICAS_EMOCIONALES', 'Técnicas Emocionales Adaptadas'), ('ASESORAMIENTO_NUTRICIONAL', 'Asesoramiento Nutricional'), ('OTRO', 'Otro')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='specialty',
        ),
        migrations.AddField(
            model_name='worker',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='workers', to='workers.specialty'),
        ),
    ]
