# Generated by Django 5.2.7 on 2025-11-15 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_address_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator(message="El formato del teléfono debe ser: '+[código país] [15 dígitos]'. Ej: +34 123456789012345", regex='^\\+\\d{1,5} \\d{15}$')]),
        ),
    ]
